FROM python:3.11-slim

WORKDIR /app

# Instala dependências de sistema para FAISS e build
RUN apt-get update && apt-get install -y build-essential git curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "app-csv-openai:app", "--host", "0.0.0.0", "--port", "8000"]
